### ISSUE TITLE
Get Error = could not find vanityAddresses.txt

### ISSUE THREAD

**Issue by asmj1108** [Aakash074/Darth-Vader#1]
![error](https://user-images.githubusercontent.com/63510581/104104582-57beba00-52a9-11eb-8679-719cd14fe194.png)
Hello, I got this error while debugging. 
As you can see in the description, a file named **vanityAddresses.txt** is missing. I'm not sure, if it's really missing or it's just that you have changed its name to **ExtensionsToEncrypt.txt** and forgot to also change the value in **Resources.resx**.
Thanks for helping!

**Comment by s1l3nt78** [comment]
No you need to compile the project with vanityAddresses and Extensions as resources so they are added into the project
